### ISSUE TITLE
rafdb.keras cannot be openned

### ISSUE THREAD

**Issue by dpigasin** [JLREx/PAtt-Lite#2]
patt = tf.keras.models.load_model(f'models/patt_lite/rafdb.keras', compile=False)

OSError: Unable to synchronously open file (file signature not found)

**Comment by JLREx** [comment]
Hi, have you tried downloading the file again or downloading it in a different way?

**Comment by CloudComputing-linux** [comment]
I couldn't open it either

**Comment by HeeminYang** [comment]
is it fake?

**Comment by JLREx** [comment]
Hi, we have replaced the saved model with a h5 version, this should load without issues.
