### ISSUE TITLE
Inquiry Regarding Environment Setup for PAtt-Lite Model

### ISSUE THREAD

**Issue by HeeminYang** [JLREx/PAtt-Lite#4]
Hello,

I hope this message finds you well. I am currently attempting to use the PAtt-Lite model that you have provided on your GitHub repository. However, I am encountering some difficulties in loading the model using Keras and TensorFlow.

Could you please provide some details about the environment in which the PAtt-Lite model was originally developed and saved? Specifically, I am interested in the following information:

The versions of Keras and TensorFlow used to create and save the model.
The version of Python used in your virtual environment.
This information would be extremely helpful for resolving compatibility issues I am facing. Below is the specific error message I am encountering:

ValueError: Layer 'conv1' expected 1 variables, but received 0 variables during loading. Expected: ['conv1/kernel:0']

**Comment by MeneerAbel** [comment]
I get the same error, so this would be nice indeed!

**Comment by JLREx** [comment]
Hi, we have replaced the saved model with a h5 version, this should load without issues. 
Regarding the environment and versions, we are using P100 GPU on the Kaggle platform. The model is saved with TensorFlow version 2.12.0 and Python version 3.10.12. 

Hope this helps.

**Comment by MeneerAbel** [comment]
This indeed fixed it, thanks! I have another question. Can I assume the output of model.predict() is in the same order as the confusion matrices in your paper? So ['anger', 'disgust', 'fear', 'happiness', 'neutral', 'sadness', 'surprise']?

**Comment by JLREx** [comment]
Yes, the prediction is following this order.

**Comment by HeeminYang** [comment]
thank you for the providing information
