### ISSUE TITLE
where's the inference code? or anything else?

### ISSUE THREAD

**Issue by M-U-X** [JLREx/PAtt-Lite#8]
Is this some sort of a scam, on kaggle it's listed as number #1  for FER, for multiple datasets, yet from the interest in this GitHub repository it seems useless, & even though the research paper says the source code will be available here, ,there's nothing at all

**Comment by JLREx** [comment]
Hi, we have just uploaded the training notebook. It is recommended to train on your database before evaluating the model for optimal performance.
